import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const spaceMono = localFont({
	src: [
		{
			path: './fonts/SpaceMono-Regular.ttf',
			weight: '500',
		},
		{
			path: './fonts/SpaceMono-Bold.ttf',
			weight: '700',
		},
	],
	variable: '--font-space-mono',
});
const workSans = localFont({
	src: './fonts/WorkSans.ttf',
	variable: '--font-work-sans',
	weight: '100 200 300 400 500 600 700 800 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${workSans.variable} ${spaceMono.variable} antialiased`}>{children}</body>
		</html>
	);
}
